---
title: "RWorksheet_Compay#1.Rmd."
author: "Gabriel A. Compay"
date: "2024-09-04"
output: pdf_document
---
```{r}
# Create the vector 'age'
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29,
         35, 31, 27, 22, 37, 34, 19, 20, 57, 49,
         50, 37, 46, 25, 17, 37, 42, 53, 41, 51,
         35, 24, 33, 41)

# Find the number of data points
num_data_points <- length(age)

num_data_points

```
```{r}
# Calculate the reciprocal of each value
reciprocals <- 1 / age

reciprocals
```
```{r}
# Create the new vector 'new_age'
new_age <- c(age, 0, age)

new_age
```
```{r}
# Sort the values in 'age'
sorted_age <- sort(age)

sorted_age
```
```{r}
min_age <- min(age)
max_age <- max(age)
min_age
max_age
```
```{r}
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5, 2.3, 2.5, 2.3, 2.4, 2.7)
length(data)
```
```{r}
doubled_data <- data * 2
doubled_data
```
```{r}
integers <- seq(1, 100)

integers <- 1:100
integers
```
```{r}
numbers <- seq(20, 60)

numbers <- 20:60
numbers
```
```{r}
numbers <- 20:60
mean_value <- mean(numbers)
mean_value
```
```{r}
numbers <- 51:91
sum_value <- sum(numbers)
sum_value
```
```{r}
integers <- 1:1000
integers
```
```{r}
subset_data <- integers[integers >= 8.1 & integers <= 8.4]
subset_data
```
```{r}
max_value <- max(integers[integers <= 10])
max_value
```
```{r}
numbers <- seq(1, 100)

result <- Filter(function(i) { all(i %% c(3, 5, 7) != 0) }, numbers)

result
```
```{r}
backwards_sequence <- rev(seq(1, 100))
backwards_sequence
```
```{r}
numbers <- seq(1, 24)

multiples <- numbers[numbers %% 3 == 0 | numbers %% 5 == 0]

sum_multiples <- sum(multiples)

numbers
multiples
sum_multiples
```
```{r}
# x <- {0 + x + 5 + }
```
```{r}
# Set up the vector named score
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75, 77)
score_2 <- score[2]

score_3 <- score[3]

score_2
score_3
```
```{r}
# Create the vector a
a <- c(1, 2, NA, 4, NA, 6, 7)

print(a, na.print="-999")
```
```{r}
name = readline(prompt="Input your name:Gabriel A. Compay ")
age = readline(prompt="Input your age: unknown ")
print(paste("My name is", name, "and I am", age, "years old."))
print(R.version.string)
```
